//cart
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
export const DECREASE_ITEM_QUATITY = 'DECREASE_ITEM_QUANTITY'
export const ADJUST_ITEM_QUANTITY = 'ADJUST_ITEM_QUANTITY'

//address
export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';

//auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

