name: Python package

on: [push]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd Backend
        python3 -m pip install --upgrade pip
        pip3 install pytest
        pip3 install -r requirements.txt
    - name: Test with pytest
      run: |
        cd Backend/Tests
        pytest
