name: Python package

on: [push]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd Backend
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        cd Tests
        pytest
