name: Node.js CI

on: [push]


jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        yarn
    - name: Run Tests
      run: |
        cd frontend
        npm test
    
