name: Node.js CI

on:[push]


jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Delete Old Modules
      run: |
        cd frontend
        rm -rf node_modules
    - name: Install dependencies
      run: |
        cd frontend
        yarn
    - name: Run Tests
      run: |
        cd frontend
        npm test
    
        npm update
        npm ci
    - name: Test with Jest
      run: |
        cd frontend
        npm test
